const listeningScoreMap = {
    40: 9,
    39: 9,
    38: 8.5,
    37: 8.5,
    36: 8,
    35: 8,
    34: 7.5,
    33: 7.5,
    32: 7.5,
    31: 7,
    30: 7,
    29: 6.5,
    28: 6.5,
    27: 6.5,
    26: 6.5,
    25: 6,
    24: 6,
    23: 6,
    22: 5.5,
    21: 5.5,
    20: 5.5,
    19: 5.5,
    18: 5.5,
    17: 5,
    16: 5,
    15: 4.5,
    14: 4.5,
    13: 4.5,
    12: 4,
    11: 4,
    10: 4,
    9: 3.5,
    8: 3.5,
    7: 3.0,
    6: 3.0,
    5: 2.5,
    4: 2.5,
    3: 0,
    2: 0,
    1: 0,
    0: 0,
};

const readingScoreMap = {
    40: 9,
    39: 9,
    38: 8.5,
    37: 8.5,
    36: 8,
    35: 8,
    34: 7.5,
    33: 7.5,
    32: 7,
    31: 7,
    30: 7,
    29: 6.5,
    28: 6.5,
    27: 6.5,
    26: 6,
    25: 6,
    24: 6,
    23: 6,
    22: 5.5,
    21: 5.5,
    20: 5.5,
    19: 5.5,
    18: 5,
    17: 5,
    16: 5,
    15: 5,
    14: 4.5,
    13: 4.5,
    12: 4,
    11: 4,
    10: 4,
    9: 3.5,
    8: 3.5,
    7: 3.0,
    6: 3.0,
    5: 2.5,
    4: 2.5,
    3: 0,
    2: 0,
    1: 0,
    0: 0,
};

const offerMap = {
    0: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    0.5: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    1: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    1.5: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    2: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    2.5: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    3: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    3.5: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    4: "Our Pre-Intermediate groups are designed to strengthen your foundation. The first lesson is completely FREE. Ready to give it a try?",
    4.5: "Our Intermediate groups are perfect for you! The first lesson is absolutely FREE. Do you want to give it a try?",
    5: "Our Intermediate groups are perfect for you! The first lesson is absolutely FREE. Do you want to give it a try?",
    5.5: "You’re set for our IELTS Novice course! Dive into essential IELTS preparation with your first lesson FREE. Want to join?",
    6: "Our IELTS Standard course will refine your strategies for a higher band. First lesson is FREE! Ready to start?",
    6.5: "Our IELTS Standard course will refine your strategies for a higher band. First lesson is FREE! Ready to start?",
    7: " The IELTS Expert course is a perfect fit to master advanced techniques. Your first lesson is FREE! Would you like to try?",
    7.5: " The IELTS Expert course is a perfect fit to master advanced techniques. Your first lesson is FREE! Would you like to try?",
    8: "Step into our IELTS Ultimate course and polish your skills for the top band. First lesson is FREE. Are you in?",
    8.5: "Step into our IELTS Ultimate course and polish your skills for the top band. First lesson is FREE. Are you in?",
    9: "Step into our IELTS Ultimate course and polish your skills for the top band. First lesson is FREE. Are you in?",
};

export { listeningScoreMap, readingScoreMap, offerMap };
